blueprint:
  name: Door Activated Light
  domain: automation
  source_url: https://github.com/nickneos/HA-Blueprints/blob/main/door_light.yaml
  input:
    trigger_door:
      name: Door Sensor
      default: binary_sensor.none
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    trigger_cover:
      name: Cover Sensor
      default: cover.none
      selector:
        entity:
          domain: cover
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to wait until the light should be turned off.
      default:
        minutes: 5
      selector:
        duration:
    below_elevation:
      name: Below solar elevation
      description: Solar elevation is the angle between the sun and the horizon. 
        Negative values mean the sun is below the horizon. This automation will 
        only run if the solar elevation is below the value you set. Leave the 
        value at 90 if you want the automation to always run regardless of the
        solar elevation.
      default: 90
      selector:
        number:
          min: -90.0
          max: 90.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
    presence_constraint:
      name: Someone Home Contsraint
      description: Enable if you only want this automation to run if someone is home.
        NOTE this is based on the person domain not the device_tracker domain.
      default: false
      selector:
        boolean:

mode: restart
max_exceeded: silent

variables:
  below_elevation: !input 'below_elevation'
  is_below_elevation: "{{ state_attr('sun.sun','elevation') <= (below_elevation | float)}}"
  presence_enabled: !input 'presence_constraint'
  presence_disabled: "{{ not presence_enabled }}"
  someone_home: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"


trigger:
  - platform: state
    entity_id: !input trigger_door
    from: 'off'
    to: 'on'
    id: door
  - platform: state
    entity_id: !input trigger_cover
    from: 'closed'
    to: 'open'
    for: '00:00:01'
    id: cover

condition:
  - "{{ is_below_elevation }}"
  - "{{ someone_home or presence_disabled }}"

action:
- service: light.turn_on
  target: !input 'light_target'
- choose:
  - conditions:
    - condition: trigger
      id: door
    sequence:
    - wait_for_trigger:
        platform: state
        entity_id: !input 'trigger_door'
        from: 'on'
        to: 'off'
  - conditions:
    - condition: trigger
      id: cover
    sequence:
    - wait_for_trigger:
        platform: state
        entity_id: !input 'trigger_cover'
        from: 'open'
        to: 'closed'
        for: '00:00:01'
  default: []
- delay: !input 'no_motion_wait'
- service: light.turn_off
  target: !input 'light_target'
