blueprint:
  name: Light Off When Room Unoccupied
  description: Turns off a light, when no motion detected in room for a certain amount of time.
  domain: automation
  source_url: https://github.com/nickneos/HA-Blueprints/blob/main/turn_off_light.yaml
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_entity:
      name: Light(s)
      selector:
        entity:
          domain: light
          multiple: true
    occupied_on_media_enabled:
      name: Enable Media Occupancy
      description: If a media player is on, consider the room occupied, therefore disable turning off light
      default: false
      selector:
        boolean:
    media_players:
      name: Media Player(s)
      description: Use this if you enabled previous option
      default: [media_player.none]
      selector:
        entity:
          domain: media_player
          multiple: true
    no_motion_duration:
      name: Unoccupied Duration
      description: Time to wait until the light should be turned off.
      default:
        hours: 0
        minutes: 15
        seconds: 0
      selector:
        duration:

mode: restart
max_exceeded: silent

variables:
  lights: !input 'light_entity'
  light_is_on: 
    "{{ expand(lights) | selectattr('state', '==', 'on')
    | list | count > 0 }}"
  occupied_on_media_enabled: !input occupied_on_media_enabled
  media_players: !input 'media_players'
  media_is_playing:
    "{{ expand(media_players) | selectattr('state', '==', 'on')
    | list | count > 0 }}"

trigger:
  platform: state
  entity_id: !input 'motion_sensor'
  from: 'off'
  to: 'on'

condition:
  - "{{ light_is_on }}"

action:
- wait_for_trigger:
    platform: state
    entity_id: !input 'motion_sensor'
    from: 'on'
    to: 'off'
- delay: !input 'no_motion_duration'
- condition: 
    - "{{ not (occupied_on_media_enabled and media_is_playing) }}"
- service: light.turn_off
  data: {}
  target:
    entity_id: !input 'light_entity'
